spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  cloud:
    gateway:
      routes:
      - id: spring-user
        uri: lb://spring-user
        predicates:
        - Path=/spring-user/**
        filters:
        - StripPrefix=1
      - id: spring-auth
        uri: lb://spring-auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
