spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sleuth:
        web:
          client:
            enabled: true
        sampler:
          probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://192.168.3.15:9411/ # 指定了 Zipkin 服务器的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
      appname: ${spring.application.name}
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2

feign:
   hystrix:
      enabled: true
   compression:
      request:
         enabled: true # 开启请求压缩
      response:
         enabled: true # 开启响应压缩

hystrix:
   command:
      default:
        execution:
          isolation:
                 strategy: THREAD
                 thread:
                     timeoutInMilliseconds: 500
                     interruptOnTimeout: true
                     interruptOnCancel: true
                 semaphore:
                    maxConcurrentRequests: 1000
          fallback:
             isolation:
                 semaphore:
                    maxConcurrentRequests: 1000
   threadpool:
      default:
          coreSize: 100
          maxQueueSize: 1500
          queueSizeRejectionThreshold: 1000

management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 3000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    ServerListRefreshInterval: 3000

logging.level.org.springframework.security: DEBUG