eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8767/eureka/
    registry-fetch-interval-seconds: 5
  instance:
      appname: ${spring.application.name}
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2