zuul:
#   ignoredServices: '*'
   routes:
        user:
           path: /spring-user/**
           serviceId: spring-user
        auth:
           path: /auth/**
           serviceId: spring-auth
        backend:
            path: /backend/**
            serviceId: spring-backend-center
   sensitive-headers: