spring:
  profiles:
    active: dev
  application:
    name: spring-config
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: /
  cloud:
      config:
        server:
          git:
            uri: https://github.com/cby86/cloud.git
            username:
            password:
            search-paths: src*
server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2



