spring:
  profiles:
    active: dev
  application:
    name: spring-register-server
server:
  port: 8761

eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
     enable-self-preservation: false
     eviction-interval-timer-in-ms: 4000